seed: 616
train:
  dataloader:
    path: './data/'
    patchsize: [64,64]
    margin: [80,80]
    batch: 512
    resize: [128,128]
    num_workers: 4

  model:
    z_dim: 256
    hidden_dim: [16,32,64,128,256]
    input_size: [1,128,128]
    lamda: 0.5
    beta: 1.0
    log_path: './logs/cevae/'
    save_path: './saved_models/cevae/'

  optimizer:
    lr: 0.0001
    epochs: 1000
    weight_decay: 0.0005

  